name: ActivateHook
main: com.github.artox.ActivateHook.Main
version: 1.0
commands:
   activate_forum_account:
      description: Activates the forum account
      usage: /activate_forum_account <forumaccname>
      permission: mc_accountlog.activate_forum_account
      permission-message: You dont have permission!
